/* tslint:disable */
/* eslint-disable */
/**
 * OpenGoPro HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { OtaStatus } from './OtaStatus.js';
import {
    OtaStatusFromJSON,
    OtaStatusFromJSONTyped,
    OtaStatusToJSON,
} from './OtaStatus.js';

/**
 * 
 * @export
 * @interface GPCAMERAFIRMWAREUPDATEV2200Response
 */
export interface GPCAMERAFIRMWAREUPDATEV2200Response {
    /**
     * 
     * @type {number}
     * @memberof GPCAMERAFIRMWAREUPDATEV2200Response
     */
    bytesComplete?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GPCAMERAFIRMWAREUPDATEV2200Response
     */
    complete?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GPCAMERAFIRMWAREUPDATEV2200Response
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof GPCAMERAFIRMWAREUPDATEV2200Response
     */
    sha1?: string;
    /**
     * 
     * @type {OtaStatus}
     * @memberof GPCAMERAFIRMWAREUPDATEV2200Response
     */
    status?: OtaStatus;
}

/**
 * Check if a given object implements the GPCAMERAFIRMWAREUPDATEV2200Response interface.
 */
export function instanceOfGPCAMERAFIRMWAREUPDATEV2200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GPCAMERAFIRMWAREUPDATEV2200ResponseFromJSON(json: any): GPCAMERAFIRMWAREUPDATEV2200Response {
    return GPCAMERAFIRMWAREUPDATEV2200ResponseFromJSONTyped(json, false);
}

export function GPCAMERAFIRMWAREUPDATEV2200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GPCAMERAFIRMWAREUPDATEV2200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bytesComplete': !exists(json, 'bytes_complete') ? undefined : json['bytes_complete'],
        'complete': !exists(json, 'complete') ? undefined : json['complete'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'sha1': !exists(json, 'sha1') ? undefined : json['sha1'],
        'status': !exists(json, 'status') ? undefined : OtaStatusFromJSON(json['status']),
    };
}

export function GPCAMERAFIRMWAREUPDATEV2200ResponseToJSON(value?: GPCAMERAFIRMWAREUPDATEV2200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bytes_complete': value.bytesComplete,
        'complete': value.complete,
        'message': value.message,
        'sha1': value.sha1,
        'status': OtaStatusToJSON(value.status),
    };
}

