/* tslint:disable */
/* eslint-disable */
/**
 * OpenGoPro HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { OtaStatus } from './OtaStatus.js';
import {
    OtaStatusFromJSON,
    OtaStatusFromJSONTyped,
    OtaStatusToJSON,
} from './OtaStatus.js';

/**
 * 
 * @export
 * @interface GPCAMERAFWUPDATEDOWNLOADFILE200Response
 */
export interface GPCAMERAFWUPDATEDOWNLOADFILE200Response {
    /**
     * 
     * @type {OtaStatus}
     * @memberof GPCAMERAFWUPDATEDOWNLOADFILE200Response
     */
    status?: OtaStatus;
}

/**
 * Check if a given object implements the GPCAMERAFWUPDATEDOWNLOADFILE200Response interface.
 */
export function instanceOfGPCAMERAFWUPDATEDOWNLOADFILE200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GPCAMERAFWUPDATEDOWNLOADFILE200ResponseFromJSON(json: any): GPCAMERAFWUPDATEDOWNLOADFILE200Response {
    return GPCAMERAFWUPDATEDOWNLOADFILE200ResponseFromJSONTyped(json, false);
}

export function GPCAMERAFWUPDATEDOWNLOADFILE200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GPCAMERAFWUPDATEDOWNLOADFILE200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : OtaStatusFromJSON(json['status']),
    };
}

export function GPCAMERAFWUPDATEDOWNLOADFILE200ResponseToJSON(value?: GPCAMERAFWUPDATEDOWNLOADFILE200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': OtaStatusToJSON(value.status),
    };
}

