/* tslint:disable */
/* eslint-disable */
/**
 * OpenGoPro HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GPCAMERACUSTOMPRESETUPDATERequest
 */
export interface GPCAMERACUSTOMPRESETUPDATERequest {
    /**
     * utf-8 encoded target custom preset name which obeys the following:
     * 
     * - must be between 1 and 16 characters (inclusive)
     * - No special characters outside of the following languages: English, French,
     *   Italian, German, Spanish, Portuguese, Swedish, Russian
     * 
     * @type {string}
     * @memberof GPCAMERACUSTOMPRESETUPDATERequest
     */
    customName?: string;
    /**
     * | ID | Name | Summary |
     * | -- | ---- | ------- |
     * | 0 | PRESET_ICON_VIDEO |  |
     * | 1 | PRESET_ICON_ACTIVITY |  |
     * | 2 | PRESET_ICON_CINEMATIC |  |
     * | 3 | PRESET_ICON_PHOTO |  |
     * | 4 | PRESET_ICON_LIVE_BURST |  |
     * | 5 | PRESET_ICON_BURST |  |
     * | 6 | PRESET_ICON_PHOTO_NIGHT |  |
     * | 7 | PRESET_ICON_TIMEWARP |  |
     *  | 8 | PRESET_ICON_TIMELAPSE |  |
     * | 9 | PRESET_ICON_NIGHTLAPSE |  |
     * | 10 | PRESET_ICON_SNAIL |  |
     * | 11 | PRESET_ICON_VIDEO_2 |  |
     * | 13 | PRESET_ICON_PHOTO_2 |  |
     * | 14 | PRESET_ICON_PANORAMA |  |
     * | 15 | PRESET_ICON_BURST_2 |  |
     * | 16 | PRESET_ICON_TIMEWARP_2 |  |
     * | 17 | PRESET_ICON_TIMELAPSE_2 |  |
     *  | 18 | PRESET_ICON_CUSTOM |  |
     * | 19 | PRESET_ICON_AIR |  |
     * | 20 | PRESET_ICON_BIKE |  |
     * | 21 | PRESET_ICON_EPIC |  |
     * | 22 | PRESET_ICON_INDOOR |  |
     * | 23 | PRESET_ICON_MOTOR |  |
     * | 24 | PRESET_ICON_MOUNTED |  |
     *  | 25 | PRESET_ICON_OUTDOOR |  |
     * | 26 | PRESET_ICON_POV |  |
     * | 27 | PRESET_ICON_SELFIE |  |
     * | 28 | PRESET_ICON_SKATE |  |
     * | 29 | PRESET_ICON_SNOW |  |
     * | 30 | PRESET_ICON_TRAIL |  |
     * | 31 | PRESET_ICON_TRAVEL |  |
     * | 32 | PRESET_ICON_WATER |  |
     * | 33 | PRESET_ICON_LOOPING |  |
     * | 58 | PRESET_ICON_BASIC |  |
     * | 59 | PRESET_ICON_ULTRA_SLO_MO |  |
     * | 60 | PRESET_ICON_STANDARD_ENDURANCE |  |
     * | 61 | PRESET_ICON_ACTIVITY_ENDURANCE |  |
     * | 62 | PRESET_ICON_CINEMATIC_ENDURANCE |  |
     * | 63 | PRESET_ICON_SLOMO_ENDURANCE |  |
     * | 64 | PRESET_ICON_STATIONARY_1 |  |
     * | 65 | PRESET_ICON_STATIONARY_2 |  |
     * | 66 | PRESET_ICON_STATIONARY_3 |  |
     * | 67 | PRESET_ICON_STATIONARY_4 |  |
     * | 70 | PRESET_ICON_SIMPLE_SUPER_PHOTO |  |
     * | 71 | PRESET_ICON_SIMPLE_NIGHT_PHOTO |  |
     * | 73 | PRESET_ICON_HIGHEST_QUALITY_VIDEO |  |
     * | 74 | PRESET_ICON_STANDARD_QUALITY_VIDEO |  |
     * | 75 | PRESET_ICON_BASIC_QUALITY_VIDEO |  |
     * | 76 | PRESET_ICON_STAR_TRAIL |  |
     * | 77 | PRESET_ICON_LIGHT_PAINTING |  |
     * | 78 | PRESET_ICON_LIGHT_TRAIL |  |
     * | 79 | PRESET_ICON_FULL_FRAME |  |
     * | 1000 | PRESET_ICON_TIMELAPSE_PHOTO |  |
     * | 1001 | PRESET_ICON_NIGHTLAPSE_PHOTO |  |
     * @type {number}
     * @memberof GPCAMERACUSTOMPRESETUPDATERequest
     */
    iconId?: GPCAMERACUSTOMPRESETUPDATERequestIconIdEnum;
    /**
     * | ID | Name | Summary |
     * | -- | ---- | ------- |
     * | 0 | PRESET_TITLE_ACTIVITY |  |
     * | 1 | PRESET_TITLE_STANDARD |  |
     * | 2 | PRESET_TITLE_CINEMATIC |  |
     * | 3 | PRESET_TITLE_PHOTO |  |
     * | 4 | PRESET_TITLE_LIVE_BURST |  |
     * | 5 | PRESET_TITLE_BURST |  |
     * | 6 | PRESET_TITLE_NIGHT |  |
     * | 7 | PRESET_TITLE_TIME_WARP |  |
     *  | 8 | PRESET_TITLE_TIME_LAPSE |  |
     * | 9 | PRESET_TITLE_NIGHT_LAPSE |  |
     * | 10 | PRESET_TITLE_VIDEO |  |
     * | 11 | PRESET_TITLE_SLOMO |  |
     * | 13 | PRESET_TITLE_PHOTO_2 |  |
     * | 14 | PRESET_TITLE_PANORAMA |  |
     * | 16 | PRESET_TITLE_TIME_WARP_2 |  |
     * | 18 | PRESET_TITLE_CUSTOM |  |
     * | 19 | PRESET_TITLE_AIR |  |
     * | 20 | PRESET_TITLE_BIKE |  |
     * | 21 | PRESET_TITLE_EPIC |  |
     * | 22 | PRESET_TITLE_INDOOR |  |
     *  | 23 | PRESET_TITLE_MOTOR |  |
     * | 24 | PRESET_TITLE_MOUNTED |  |
     * | 25 | PRESET_TITLE_OUTDOOR |  |
     * | 26 | PRESET_TITLE_POV |  |
     * | 27 | PRESET_TITLE_SELFIE |  |
     * | 28 | PRESET_TITLE_SKATE |  |
     * | 29 | PRESET_TITLE_SNOW |  |
     * | 30 | PRESET_TITLE_TRAIL |  |
     * | 31 | PRESET_TITLE_TRAVEL |  |
     * | 32 | PRESET_TITLE_WATER |  |
     *  | 33 | PRESET_TITLE_LOOPING |  |
     * | 58 | PRESET_TITLE_BASIC |  |
     * | 59 | PRESET_TITLE_ULTRA_SLO_MO |  |
     * | 60 | PRESET_TITLE_STANDARD_ENDURANCE |  |
     * | 61 | PRESET_TITLE_ACTIVITY_ENDURANCE |  |
     * | 62 | PRESET_TITLE_CINEMATIC_ENDURANCE |  |
     * | 63 | PRESET_TITLE_SLOMO_ENDURANCE |  |
     * | 64 | PRESET_TITLE_STATIONARY_1 |  |
     * | 65 | PRESET_TITLE_STATIONARY_2 |  |
     * | 66 | PRESET_TITLE_STATIONARY_3 |  |
     * | 67 | PRESET_TITLE_STATIONARY_4 |  |
     * | 68 | PRESET_TITLE_SIMPLE_VIDEO |  |
     * | 69 | PRESET_TITLE_SIMPLE_TIME_WARP |  |
     * | 70 | PRESET_TITLE_SIMPLE_SUPER_PHOTO |  |
     * | 71 | PRESET_TITLE_SIMPLE_NIGHT_PHOTO |  |
     * | 72 | PRESET_TITLE_SIMPLE_VIDEO_ENDURANCE |  |
     * | 73 | PRESET_TITLE_HIGHEST_QUALITY |  |
     * | 74 | PRESET_TITLE_EXTENDED_BATTERY |  |
     * | 75 | PRESET_TITLE_LONGEST_BATTERY |  |
     * | 76 | PRESET_TITLE_STAR_TRAIL |  |
     * | 77 | PRESET_TITLE_LIGHT_PAINTING |  |
     * | 78 | PRESET_TITLE_LIGHT_TRAIL |  |
     * | 79 | PRESET_TITLE_FULL_FRAME |  |
     * | 82 | PRESET_TITLE_STANDARD_QUALITY_VIDEO |  |
     * | 83 | PRESET_TITLE_BASIC_QUALITY_VIDEO |  |
     * | 93 | PRESET_TITLE_HIGHEST_QUALITY_VIDEO |  |
     * | 94 | PRESET_TITLE_USER_DEFINED_CUSTOM_NAME |  |
     * @type {number}
     * @memberof GPCAMERACUSTOMPRESETUPDATERequest
     */
    titleId?: GPCAMERACUSTOMPRESETUPDATERequestTitleIdEnum;
}


/**
 * @export
 */
export const GPCAMERACUSTOMPRESETUPDATERequestIconIdEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7,
    NUMBER_8: 8,
    NUMBER_9: 9,
    NUMBER_10: 10,
    NUMBER_11: 11,
    NUMBER_13: 13,
    NUMBER_14: 14,
    NUMBER_15: 15,
    NUMBER_16: 16,
    NUMBER_17: 17,
    NUMBER_18: 18,
    NUMBER_19: 19,
    NUMBER_20: 20,
    NUMBER_21: 21,
    NUMBER_22: 22,
    NUMBER_23: 23,
    NUMBER_24: 24,
    NUMBER_25: 25,
    NUMBER_26: 26,
    NUMBER_27: 27,
    NUMBER_28: 28,
    NUMBER_29: 29,
    NUMBER_30: 30,
    NUMBER_31: 31,
    NUMBER_32: 32,
    NUMBER_33: 33,
    NUMBER_58: 58,
    NUMBER_59: 59,
    NUMBER_60: 60,
    NUMBER_61: 61,
    NUMBER_62: 62,
    NUMBER_63: 63,
    NUMBER_64: 64,
    NUMBER_65: 65,
    NUMBER_66: 66,
    NUMBER_67: 67,
    NUMBER_70: 70,
    NUMBER_71: 71,
    NUMBER_73: 73,
    NUMBER_74: 74,
    NUMBER_75: 75,
    NUMBER_76: 76,
    NUMBER_77: 77,
    NUMBER_78: 78,
    NUMBER_79: 79,
    NUMBER_1000: 1000,
    NUMBER_1001: 1001
} as const;
export type GPCAMERACUSTOMPRESETUPDATERequestIconIdEnum = typeof GPCAMERACUSTOMPRESETUPDATERequestIconIdEnum[keyof typeof GPCAMERACUSTOMPRESETUPDATERequestIconIdEnum];

/**
 * @export
 */
export const GPCAMERACUSTOMPRESETUPDATERequestTitleIdEnum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7,
    NUMBER_8: 8,
    NUMBER_9: 9,
    NUMBER_10: 10,
    NUMBER_11: 11,
    NUMBER_13: 13,
    NUMBER_14: 14,
    NUMBER_16: 16,
    NUMBER_18: 18,
    NUMBER_19: 19,
    NUMBER_20: 20,
    NUMBER_21: 21,
    NUMBER_22: 22,
    NUMBER_23: 23,
    NUMBER_24: 24,
    NUMBER_25: 25,
    NUMBER_26: 26,
    NUMBER_27: 27,
    NUMBER_28: 28,
    NUMBER_29: 29,
    NUMBER_30: 30,
    NUMBER_31: 31,
    NUMBER_32: 32,
    NUMBER_33: 33,
    NUMBER_58: 58,
    NUMBER_59: 59,
    NUMBER_60: 60,
    NUMBER_61: 61,
    NUMBER_62: 62,
    NUMBER_63: 63,
    NUMBER_64: 64,
    NUMBER_65: 65,
    NUMBER_66: 66,
    NUMBER_67: 67,
    NUMBER_68: 68,
    NUMBER_69: 69,
    NUMBER_70: 70,
    NUMBER_71: 71,
    NUMBER_72: 72,
    NUMBER_73: 73,
    NUMBER_74: 74,
    NUMBER_75: 75,
    NUMBER_76: 76,
    NUMBER_77: 77,
    NUMBER_78: 78,
    NUMBER_79: 79,
    NUMBER_82: 82,
    NUMBER_83: 83,
    NUMBER_93: 93,
    NUMBER_94: 94
} as const;
export type GPCAMERACUSTOMPRESETUPDATERequestTitleIdEnum = typeof GPCAMERACUSTOMPRESETUPDATERequestTitleIdEnum[keyof typeof GPCAMERACUSTOMPRESETUPDATERequestTitleIdEnum];


/**
 * Check if a given object implements the GPCAMERACUSTOMPRESETUPDATERequest interface.
 */
export function instanceOfGPCAMERACUSTOMPRESETUPDATERequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GPCAMERACUSTOMPRESETUPDATERequestFromJSON(json: any): GPCAMERACUSTOMPRESETUPDATERequest {
    return GPCAMERACUSTOMPRESETUPDATERequestFromJSONTyped(json, false);
}

export function GPCAMERACUSTOMPRESETUPDATERequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GPCAMERACUSTOMPRESETUPDATERequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customName': !exists(json, 'custom_name') ? undefined : json['custom_name'],
        'iconId': !exists(json, 'icon_id') ? undefined : json['icon_id'],
        'titleId': !exists(json, 'title_id') ? undefined : json['title_id'],
    };
}

export function GPCAMERACUSTOMPRESETUPDATERequestToJSON(value?: GPCAMERACUSTOMPRESETUPDATERequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'custom_name': value.customName,
        'icon_id': value.iconId,
        'title_id': value.titleId,
    };
}

