/* tslint:disable */
/* eslint-disable */
/**
 * OpenGoPro HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GPCAMERAOPENGOPROVERSION200Response
 */
export interface GPCAMERAOPENGOPROVERSION200Response {
    /**
     * Open GoPro version
     * @type {string}
     * @memberof GPCAMERAOPENGOPROVERSION200Response
     */
    version?: string;
}

/**
 * Check if a given object implements the GPCAMERAOPENGOPROVERSION200Response interface.
 */
export function instanceOfGPCAMERAOPENGOPROVERSION200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GPCAMERAOPENGOPROVERSION200ResponseFromJSON(json: any): GPCAMERAOPENGOPROVERSION200Response {
    return GPCAMERAOPENGOPROVERSION200ResponseFromJSONTyped(json, false);
}

export function GPCAMERAOPENGOPROVERSION200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GPCAMERAOPENGOPROVERSION200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function GPCAMERAOPENGOPROVERSION200ResponseToJSON(value?: GPCAMERAOPENGOPROVERSION200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
    };
}

