/* tslint:disable */
/* eslint-disable */
/**
 * OpenGoPro HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * A grouped (i.e. burst, lapse, etc.) media item
 * 
 * Note that each property actually comes as a string but is specified here using its functional value.
 * 
 * @export
 * @interface GroupedMediaListItem
 */
export interface GroupedMediaListItem {
    /**
     * ID of first member in the group
     * @type {number}
     * @memberof GroupedMediaListItem
     */
    b: number;
    /**
     * Creation time in seconds since epoch
     * @type {number}
     * @memberof GroupedMediaListItem
     */
    cre: number;
    /**
     * Group Identifier
     * @type {number}
     * @memberof GroupedMediaListItem
     */
    g: number;
    /**
     * Low resolution video size
     * @type {number}
     * @memberof GroupedMediaListItem
     */
    glrv?: number;
    /**
     * Media list session identifier
     * @type {string}
     * @memberof GroupedMediaListItem
     */
    id?: string;
    /**
     * ID of last member in the group
     * @type {number}
     * @memberof GroupedMediaListItem
     */
    l: number;
    /**
     * Low resolution file size. -1 if there is no LRV file
     * @type {number}
     * @memberof GroupedMediaListItem
     */
    ls?: number;
    /**
     * File ID's that are missing or deleted
     * @type {Array<number>}
     * @memberof GroupedMediaListItem
     */
    m: Array<number>;
    /**
     * Time file was last modified in seconds since epoch
     * @type {number}
     * @memberof GroupedMediaListItem
     */
    mod: number;
    /**
     * Media filename
     * @type {string}
     * @memberof GroupedMediaListItem
     */
    n: string;
    /**
     * Number of files in the group
     * @type {number}
     * @memberof GroupedMediaListItem
     */
    s: number;
    /**
     * Group Type (b -> burst, c -> continuous shot, n -> night lapse, t -> time lapse)
     * @type {string}
     * @memberof GroupedMediaListItem
     */
    t: GroupedMediaListItemTEnum;
}


/**
 * @export
 */
export const GroupedMediaListItemTEnum = {
    B: 'b',
    C: 'c',
    N: 'n',
    T: 't'
} as const;
export type GroupedMediaListItemTEnum = typeof GroupedMediaListItemTEnum[keyof typeof GroupedMediaListItemTEnum];


/**
 * Check if a given object implements the GroupedMediaListItem interface.
 */
export function instanceOfGroupedMediaListItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "b" in value;
    isInstance = isInstance && "cre" in value;
    isInstance = isInstance && "g" in value;
    isInstance = isInstance && "l" in value;
    isInstance = isInstance && "m" in value;
    isInstance = isInstance && "mod" in value;
    isInstance = isInstance && "n" in value;
    isInstance = isInstance && "s" in value;
    isInstance = isInstance && "t" in value;

    return isInstance;
}

export function GroupedMediaListItemFromJSON(json: any): GroupedMediaListItem {
    return GroupedMediaListItemFromJSONTyped(json, false);
}

export function GroupedMediaListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupedMediaListItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'b': json['b'],
        'cre': json['cre'],
        'g': json['g'],
        'glrv': !exists(json, 'glrv') ? undefined : json['glrv'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'l': json['l'],
        'ls': !exists(json, 'ls') ? undefined : json['ls'],
        'm': json['m'],
        'mod': json['mod'],
        'n': json['n'],
        's': json['s'],
        't': json['t'],
    };
}

export function GroupedMediaListItemToJSON(value?: GroupedMediaListItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'b': value.b,
        'cre': value.cre,
        'g': value.g,
        'glrv': value.glrv,
        'id': value.id,
        'l': value.l,
        'ls': value.ls,
        'm': value.m,
        'mod': value.mod,
        'n': value.n,
        's': value.s,
        't': value.t,
    };
}

