/* tslint:disable */
/* eslint-disable */
/**
 * OpenGoPro HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { OGPCAMERAINFO200ResponseInfo } from './OGPCAMERAINFO200ResponseInfo.js';
import {
    OGPCAMERAINFO200ResponseInfoFromJSON,
    OGPCAMERAINFO200ResponseInfoFromJSONTyped,
    OGPCAMERAINFO200ResponseInfoToJSON,
} from './OGPCAMERAINFO200ResponseInfo.js';

/**
 * 
 * @export
 * @interface OGPCAMERAINFO200Response
 */
export interface OGPCAMERAINFO200Response {
    /**
     * 
     * @type {OGPCAMERAINFO200ResponseInfo}
     * @memberof OGPCAMERAINFO200Response
     */
    info?: OGPCAMERAINFO200ResponseInfo;
}

/**
 * Check if a given object implements the OGPCAMERAINFO200Response interface.
 */
export function instanceOfOGPCAMERAINFO200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OGPCAMERAINFO200ResponseFromJSON(json: any): OGPCAMERAINFO200Response {
    return OGPCAMERAINFO200ResponseFromJSONTyped(json, false);
}

export function OGPCAMERAINFO200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OGPCAMERAINFO200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'info': !exists(json, 'info') ? undefined : OGPCAMERAINFO200ResponseInfoFromJSON(json['info']),
    };
}

export function OGPCAMERAINFO200ResponseToJSON(value?: OGPCAMERAINFO200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'info': OGPCAMERAINFO200ResponseInfoToJSON(value.info),
    };
}

