/* tslint:disable */
/* eslint-disable */
/**
 * OpenGoPro HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OGPCAMERAINFO200ResponseInfo
 */
export interface OGPCAMERAINFO200ResponseInfo {
    /**
     * Camera's Access Point MAC address
     * @type {string}
     * @memberof OGPCAMERAINFO200ResponseInfo
     */
    apMacAddr?: string;
    /**
     * Camera's ACcess Point SSID name
     * @type {string}
     * @memberof OGPCAMERAINFO200ResponseInfo
     */
    apSsid?: string;
    /**
     * Camera Firmware version
     * @type {string}
     * @memberof OGPCAMERAINFO200ResponseInfo
     */
    firmwareVersion?: string;
    /**
     * Camera Model Name
     * @type {string}
     * @memberof OGPCAMERAINFO200ResponseInfo
     */
    modelName?: string;
    /**
     * Camera Model integer (as string)
     * @type {string}
     * @memberof OGPCAMERAINFO200ResponseInfo
     */
    modelNumber?: string;
    /**
     * Camera serial number
     * @type {string}
     * @memberof OGPCAMERAINFO200ResponseInfo
     */
    serialNumber?: string;
}

/**
 * Check if a given object implements the OGPCAMERAINFO200ResponseInfo interface.
 */
export function instanceOfOGPCAMERAINFO200ResponseInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OGPCAMERAINFO200ResponseInfoFromJSON(json: any): OGPCAMERAINFO200ResponseInfo {
    return OGPCAMERAINFO200ResponseInfoFromJSONTyped(json, false);
}

export function OGPCAMERAINFO200ResponseInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OGPCAMERAINFO200ResponseInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apMacAddr': !exists(json, 'ap_mac_addr') ? undefined : json['ap_mac_addr'],
        'apSsid': !exists(json, 'ap_ssid') ? undefined : json['ap_ssid'],
        'firmwareVersion': !exists(json, 'firmware_version') ? undefined : json['firmware_version'],
        'modelName': !exists(json, 'model_name') ? undefined : json['model_name'],
        'modelNumber': !exists(json, 'model_number') ? undefined : json['model_number'],
        'serialNumber': !exists(json, 'serial_number') ? undefined : json['serial_number'],
    };
}

export function OGPCAMERAINFO200ResponseInfoToJSON(value?: OGPCAMERAINFO200ResponseInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ap_mac_addr': value.apMacAddr,
        'ap_ssid': value.apSsid,
        'firmware_version': value.firmwareVersion,
        'model_name': value.modelName,
        'model_number': value.modelNumber,
        'serial_number': value.serialNumber,
    };
}

