/* tslint:disable */
/* eslint-disable */
/**
 * OpenGoPro HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OGPGETLASTMEDIA200Response
 */
export interface OGPGETLASTMEDIA200Response {
    /**
     * Filename of media
     * @type {string}
     * @memberof OGPGETLASTMEDIA200Response
     */
    file?: string;
    /**
     * Directory that the media is contained in
     * @type {string}
     * @memberof OGPGETLASTMEDIA200Response
     */
    folder?: string;
}

/**
 * Check if a given object implements the OGPGETLASTMEDIA200Response interface.
 */
export function instanceOfOGPGETLASTMEDIA200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OGPGETLASTMEDIA200ResponseFromJSON(json: any): OGPGETLASTMEDIA200Response {
    return OGPGETLASTMEDIA200ResponseFromJSONTyped(json, false);
}

export function OGPGETLASTMEDIA200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OGPGETLASTMEDIA200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': !exists(json, 'file') ? undefined : json['file'],
        'folder': !exists(json, 'folder') ? undefined : json['folder'],
    };
}

export function OGPGETLASTMEDIA200ResponseToJSON(value?: OGPGETLASTMEDIA200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': value.file,
        'folder': value.folder,
    };
}

