/* tslint:disable */
/* eslint-disable */
/**
 * OpenGoPro HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { PresetGroup } from './PresetGroup.js';
import {
    PresetGroupFromJSON,
    PresetGroupFromJSONTyped,
    PresetGroupToJSON,
} from './PresetGroup.js';

/**
 * 
 * @export
 * @interface OGPPRESETSGET200Response
 */
export interface OGPPRESETSGET200Response {
    /**
     * Array of Preset Groups
     * @type {Array<PresetGroup>}
     * @memberof OGPPRESETSGET200Response
     */
    presetGroupArray?: Array<PresetGroup>;
}

/**
 * Check if a given object implements the OGPPRESETSGET200Response interface.
 */
export function instanceOfOGPPRESETSGET200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OGPPRESETSGET200ResponseFromJSON(json: any): OGPPRESETSGET200Response {
    return OGPPRESETSGET200ResponseFromJSONTyped(json, false);
}

export function OGPPRESETSGET200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OGPPRESETSGET200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'presetGroupArray': !exists(json, 'presetGroupArray') ? undefined : ((json['presetGroupArray'] as Array<any>).map(PresetGroupFromJSON)),
    };
}

export function OGPPRESETSGET200ResponseToJSON(value?: OGPPRESETSGET200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'presetGroupArray': value.presetGroupArray === undefined ? undefined : ((value.presetGroupArray as Array<any>).map(PresetGroupToJSON)),
    };
}

