/* tslint:disable */
/* eslint-disable */
/**
 * OpenGoPro HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * A single (non-grouped) media item
 * 
 * Note that each property actually comes as a string but is specified here using its functional value.
 * 
 * @export
 * @interface SingleMediaListItem
 */
export interface SingleMediaListItem {
    /**
     * Creation time in seconds since epoch
     * @type {number}
     * @memberof SingleMediaListItem
     */
    cre: number;
    /**
     * Low resolution video size
     * @type {number}
     * @memberof SingleMediaListItem
     */
    glrv?: number;
    /**
     * Low resolution file size. -1 if there is no LRV file
     * @type {number}
     * @memberof SingleMediaListItem
     */
    ls?: number;
    /**
     * Time file was last modified in seconds since epoch
     * @type {number}
     * @memberof SingleMediaListItem
     */
    mod: number;
    /**
     * Media filename
     * @type {string}
     * @memberof SingleMediaListItem
     */
    n: string;
    /**
     * Size of media in bytes
     * @type {number}
     * @memberof SingleMediaListItem
     */
    s: number;
}

/**
 * Check if a given object implements the SingleMediaListItem interface.
 */
export function instanceOfSingleMediaListItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cre" in value;
    isInstance = isInstance && "mod" in value;
    isInstance = isInstance && "n" in value;
    isInstance = isInstance && "s" in value;

    return isInstance;
}

export function SingleMediaListItemFromJSON(json: any): SingleMediaListItem {
    return SingleMediaListItemFromJSONTyped(json, false);
}

export function SingleMediaListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SingleMediaListItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cre': json['cre'],
        'glrv': !exists(json, 'glrv') ? undefined : json['glrv'],
        'ls': !exists(json, 'ls') ? undefined : json['ls'],
        'mod': json['mod'],
        'n': json['n'],
        's': json['s'],
    };
}

export function SingleMediaListItemToJSON(value?: SingleMediaListItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cre': value.cre,
        'glrv': value.glrv,
        'ls': value.ls,
        'mod': value.mod,
        'n': value.n,
        's': value.s,
    };
}

