/* tslint:disable */
/* eslint-disable */
/**
 * OpenGoPro HTTP API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * All currently known setting values indexed by setting ID
 * @export
 * @interface StateSettings
 */
export interface StateSettings {
    /**
     * **Video Resolution**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * - HERO11 Black Mini
     * - HERO11 Black
     * - HERO10 Black
     * - HERO9 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 1 | Video Resolution 4K | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     *  | 4 | Video Resolution 2 7K | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     *  | 6 | Video Resolution 2 7K 4By3 | HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 7 | Video Resolution 1440 | HERO9 Black |
     * | 9 | Video Resolution 1080 | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 18 | Video Resolution 4K 4By3 | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 24 | Video Resolution 5K | HERO9 Black |
     * | 25 | Video Resolution 5K 4By3 | HERO10 Black |
     * | 26 | Video Resolution 5 3K 8By7 | HERO11 Black Mini, HERO11 Black |
     * | 27 | Video Resolution 5 3K 4By3 | HERO11 Black Mini, HERO11 Black |
     * | 28 | Video Resolution 4K 8By7 | HERO11 Black Mini, HERO11 Black |
     * | 100 | Video Resolution 5 3K | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black |
     * | 107 | Video Resolution 5 3K 8By7 V2 | HERO12 Black |
     * | 108 | Video Resolution 4K 8By7 V2 | HERO12 Black |
     *  | 109 | Video Resolution 4K 9By16 V2 | HERO12 Black |
     * | 110 | Video Resolution 1080 9By16 V2 | HERO12 Black |
     * | 111 | Video Resolution 2 7K 4By3 V2 | HERO12 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _2?: StateSettings_2Enum;
    /**
     * **Video Fps**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * - HERO11 Black Mini
     * - HERO11 Black
     *  - HERO10 Black
     * - HERO9 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Video Fps 240 | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 1 | Video Fps 120 | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 2 | Video Fps 100 | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 5 | Video Fps 60 | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 6 | Video Fps 50 | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 8 | Video Fps 30 | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 9 | Video Fps 25 | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 10 | Video Fps 24 | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 13 | Video Fps 200 | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _3?: StateSettings_3Enum;
    /**
     * **Broadcast Fov**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * - HERO11 Black Mini
     * - HERO11 Black
     *  - HERO10 Black
     * - HERO9 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Broadcast Fov Wide | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     *  | 2 | Broadcast Fov Narrow | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     *  | 3 | Broadcast Fov Superview | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     *  | 4 | Broadcast Fov Linear | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _43?: StateSettings_43Enum;
    /**
     * **Setup Auto Power Down**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * - HERO11 Black Mini
     * - HERO11 Black
     * - HERO10 Black
     * - HERO9 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Setup Auto Power Down Never | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 1 | Setup Auto Power Down 1 Min | HERO12 Black, HERO11 Black Mini, HERO11 Black |
     * | 4 | Setup Auto Power Down 5 Min | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 6 | Setup Auto Power Down 15 Min | HERO12 Black, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 7 | Setup Auto Power Down 30 Min | HERO12 Black, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 11 | Setup Auto Power Down 8 Seconds | HERO11 Black Mini |
     * | 12 | Setup Auto Power Down 30 Seconds | HERO11 Black Mini |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _59?: StateSettings_59Enum;
    /**
     * **Video Aspect Ratio**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Video Aspect Ratio 4By3 | HERO12 Black |
     * | 1 | Video Aspect Ratio 16By9 | HERO12 Black |
     * | 3 | Video Aspect Ratio 8By7 | HERO12 Black |
     * | 4 | Video Aspect Ratio 9By16 | HERO12 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _108?: StateSettings_108Enum;
    /**
     * **Video Digital Lenses**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * - HERO11 Black Mini
     * - HERO11 Black
     * - HERO10 Black
     * - HERO9 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Video Digital Lenses Wide | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 2 | Video Digital Lenses Narrow | HERO10 Black, HERO9 Black |
     * | 3 | Video Digital Lenses Superview | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 4 | Video Digital Lenses Linear | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 7 | Video Digital Lenses Max Superview | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 8 | Video Digital Lenses Linear Plus Horizon Leveling | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 9 | Video Digital Lenses Hyperview | HERO12 Black, HERO11 Black Mini, HERO11 Black |
     * | 10 | Video Digital Lenses Linear Plus Horizon Lock | HERO12 Black, HERO11 Black Mini, HERO11 Black |
     * | 11 | Video Digital Lenses Max Hyperview | HERO12 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _121?: StateSettings_121Enum;
    /**
     * **Photo Digital Lenses**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * - HERO11 Black
     * - HERO10 Black
     *  - HERO9 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 19 | Photo Digital Lenses Narrow | HERO10 Black, HERO9 Black |
     * | 100 | Photo Digital Lenses Max Superview | HERO12 Black, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 101 | Photo Digital Lenses Wide | HERO12 Black, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 102 | Photo Digital Lenses Linear | HERO12 Black, HERO11 Black, HERO10 Black, HERO9 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _122?: StateSettings_122Enum;
    /**
     * **Multi Shot Digital Lenses**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * - HERO11 Black
     * - HERO10 Black
     * - HERO9 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 19 | Multi Shot Digital Lenses Narrow | HERO10 Black, HERO9 Black |
     * | 100 | Multi Shot Digital Lenses Max Superview | HERO10 Black |
     * | 101 | Multi Shot Digital Lenses Wide | HERO12 Black, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 102 | Multi Shot Digital Lenses Linear | HERO12 Black, HERO11 Black, HERO10 Black, HERO9 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _123?: StateSettings_123Enum;
    /**
     * **General Format**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * - HERO11 Black
     * - HERO10 Black
     *  - HERO9 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 13 | General Format Time Lapse Video | HERO12 Black, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 20 | General Format Time Lapse Photo | HERO12 Black, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 21 | General Format Night Lapse Photo | HERO12 Black, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 26 | General Format Night Lapse Video | HERO12 Black, HERO11 Black, HERO10 Black, HERO9 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _128?: StateSettings_128Enum;
    /**
     * **Setup Anti Flicker**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * - HERO11 Black Mini
     * - HERO11 Black
     * - HERO10 Black
     * - HERO9 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 2 | Setup Anti Flicker 60 Hz | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 3 | Setup Anti Flicker 50 Hz | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _134?: StateSettings_134Enum;
    /**
     * **Video Hypersmooth**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * - HERO11 Black Mini
     * - HERO11 Black
     * - HERO10 Black
     * - HERO9 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Video Hypersmooth Off | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 1 | Video Hypersmooth On | HERO12 Black, HERO11 Black Mini, HERO11 Black, HERO9 Black |
     * | 2 | Video Hypersmooth High | HERO10 Black, HERO9 Black |
     * | 3 | Video Hypersmooth Boost | HERO11 Black Mini, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 4 | Video Hypersmooth Auto Boost | HERO12 Black, HERO11 Black Mini, HERO11 Black |
     * | 100 | Video Hypersmooth Standard | HERO10 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _135?: StateSettings_135Enum;
    /**
     * **Video Horizon Levelling**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO11 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Video Horizon Levelling Off | HERO11 Black |
     * | 2 | Video Horizon Levelling Locked | HERO11 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _150?: StateSettings_150Enum;
    /**
     * **Photo Horizon Levelling**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO11 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Photo Horizon Levelling Off | HERO11 Black |
     * | 2 | Photo Horizon Levelling Locked | HERO11 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _151?: StateSettings_151Enum;
    /**
     * **Mods Max Lens Enable**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO11 Black
     * - HERO10 Black
     * - HERO9 Black
     *  
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Mods Max Lens Enable Off | HERO11 Black, HERO10 Black, HERO9 Black |
     * | 1 | Mods Max Lens Enable On | HERO11 Black, HERO10 Black, HERO9 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _162?: StateSettings_162Enum;
    /**
     * **Video Hindsight Length**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * - HERO11 Black
     * - HERO10 Black
     * - HERO9 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 2 | Video Hindsight Length 15 Seconds | HERO12 Black, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 3 | Video Hindsight Length 30 Seconds | HERO12 Black, HERO11 Black, HERO10 Black, HERO9 Black |
     * | 4 | Video Hindsight Length Off | HERO12 Black, HERO11 Black, HERO10 Black, HERO9 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _167?: StateSettings_167Enum;
    /**
     * **Photo Single Interval**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Photo Single Interval Off | HERO12 Black |
     * | 2 | Photo Single Interval 0 5 Seconds | HERO12 Black |
     * | 3 | Photo Single Interval 1 Second | HERO12 Black |
     * | 4 | Photo Single Interval 2 Seconds | HERO12 Black |
     * | 5 | Photo Single Interval 5 Seconds | HERO12 Black |
     * | 6 | Photo Single Interval 10 Seconds | HERO12 Black |
     * | 7 | Photo Single Interval 30 Seconds | HERO12 Black |
     * | 8 | Photo Single Interval 60 Seconds | HERO12 Black |
     * | 9 | Photo Single Interval 120 Seconds | HERO12 Black |
     * | 10 | Photo Single Interval 3 Seconds | HERO12 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _171?: StateSettings_171Enum;
    /**
     * **Photo Interval Duration**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Photo Interval Duration Off | HERO12 Black |
     * | 1 | Photo Interval Duration 15 Seconds | HERO12 Black |
     * | 2 | Photo Interval Duration 30 Seconds | HERO12 Black |
     * | 3 | Photo Interval Duration 1 Minute | HERO12 Black |
     * | 4 | Photo Interval Duration 5 Minutes | HERO12 Black |
     * | 5 | Photo Interval Duration 15 Minutes | HERO12 Black |
     * | 6 | Photo Interval Duration 30 Minutes | HERO12 Black |
     * | 7 | Photo Interval Duration 1 Hour | HERO12 Black |
     * | 8 | Photo Interval Duration 2 Hours | HERO12 Black |
     * | 9 | Photo Interval Duration 3 Hours | HERO12 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _172?: StateSettings_172Enum;
    /**
     * **System Power Profile**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO10 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | System Power Profile Maximum Video Performance | HERO10 Black |
     * | 1 | System Power Profile Extended Battery | HERO10 Black |
     * | 2 | System Power Profile Tripod Stationary Video | HERO10 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _173?: StateSettings_173Enum;
    /**
     * **Setup Camera Ux Mode**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * - HERO11 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Setup Camera Ux Mode Easy | HERO12 Black, HERO11 Black |
     * | 1 | Setup Camera Ux Mode Pro | HERO12 Black, HERO11 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _175?: StateSettings_175Enum;
    /**
     * **Video Easy Mode Speed**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * - HERO11 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Video Easy Mode Speed 8X Ultra Slo Mo | HERO11 Black |
     * | 1 | Video Easy Mode Speed 4X Super Slo Mo | HERO11 Black |
     * | 2 | Video Easy Mode Speed 2X Slo Mo | HERO11 Black |
     * | 3 | Video Easy Mode Speed 1X Speed Low Light | HERO11 Black |
     * | 4 | Video Easy Mode Speed Eb 4X Super Slo Mo | HERO11 Black |
     * | 5 | Video Easy Mode Speed Eb 2X Slo Mo | HERO11 Black |
     * | 6 | Video Easy Mode Speed Eb 1X Speed Low Light | HERO11 Black |
     * | 7 | Video Easy Mode Speed 8X Ultra Slo Mo 50Hz | HERO11 Black |
     * | 8 | Video Easy Mode Speed 4X Super Slo Mo 50Hz | HERO11 Black |
     * | 9 | Video Easy Mode Speed 2X Slo Mo 50Hz | HERO11 Black |
     * | 10 | Video Easy Mode Speed 1X Speed Low Light 50Hz | HERO11 Black |
     * | 11 | Video Easy Mode Speed Eb 4X Super Slo Mo 50Hz | HERO11 Black |
     * | 12 | Video Easy Mode Speed Eb 2X Slo Mo 50Hz | HERO11 Black |
     * | 13 | Video Easy Mode Speed Eb 1X Speed Low Light 50Hz | HERO11 Black |
     * | 14 | Video Easy Mode Speed Eb 8X Ultra Slo Mo | HERO11 Black |
     * | 15 | Video Easy Mode Speed Eb 8X Ultra Slo Mo 50Hz | HERO11 Black |
     * | 16 | Video Easy Mode Speed Lb 8X Ultra Slo Mo | HERO11 Black |
     * | 17 | Video Easy Mode Speed Lb 4X Super Slo Mo | HERO11 Black |
     * | 18 | Video Easy Mode Speed Lb 2X Slo Mo | HERO11 Black |
     * | 19 | Video Easy Mode Speed Lb 1X Speed Low Light | HERO11 Black |
     * | 20 | Video Easy Mode Speed Lb 8X Ultra Slo Mo 50Hz | HERO11 Black |
     * | 21 | Video Easy Mode Speed Lb 4X Super Slo Mo 50Hz | HERO11 Black |
     * | 22 | Video Easy Mode Speed Lb 2X Slo Mo 50Hz | HERO11 Black |
     * | 23 | Video Easy Mode Speed Lb 1X Speed Low Light 50Hz | HERO11 Black |
     * | 24 | Video Easy Mode Speed 2X Slo Mo 4K | HERO11 Black |
     * | 25 | Video Easy Mode Speed 4X Super Slo Mo 2 7K | HERO11 Black |
     * | 26 | Video Easy Mode Speed 2X Slo Mo 4K 50Hz | HERO11 Black |
     * | 27 | Video Easy Mode Speed 4X Super Slo Mo 2 7K 50Hz | HERO11 Black |
     * | 100 | Video Easy Mode Speed 8X Ultra Slo Mo V2 | HERO12 Black |
     * | 101 | Video Easy Mode Speed 4X Super Slo Mo V2 | HERO12 Black |
     * | 102 | Video Easy Mode Speed 2X Slo Mo V2 | HERO12 Black |
     * | 103 | Video Easy Mode Speed 1X Speed Low Light V2 | HERO12 Black |
     * | 104 | Video Easy Mode Speed 8X Ultra Slo Mo 50Hz V2 | HERO12 Black |
     * | 105 | Video Easy Mode Speed 4X Super Slo Mo 50Hz V2 | HERO12 Black |
     * | 106 | Video Easy Mode Speed 2X Slo Mo 50Hz V2 | HERO12 Black |
     * | 107 | Video Easy Mode Speed 1X Speed Low Light 50Hz V2 | HERO12 Black |
     * | 108 | Video Easy Mode Speed Lb 8X Ultra Slo Mo V2 | HERO12 Black |
     * | 109 | Video Easy Mode Speed Lb 4X Super Slo Mo V2 | HERO12 Black |
     * | 110 | Video Easy Mode Speed Lb 2X Slo Mo V2 | HERO12 Black |
     * | 111 | Video Easy Mode Speed Lb 1X Speed Low Light V2 | HERO12 Black |
     * | 112 | Video Easy Mode Speed Lb 8X Ultra Slo Mo 50Hz V2 | HERO12 Black |
     * | 113 | Video Easy Mode Speed Lb 4X Super Slo Mo 50Hz V2 | HERO12 Black |
     * | 114 | Video Easy Mode Speed Lb 2X Slo Mo 50Hz V2 | HERO12 Black |
     * | 115 | Video Easy Mode Speed Lb 1X Speed Low Light 50Hz V2 | HERO12 Black |
     * | 116 | Video Easy Mode Speed 2X Slo Mo 4K V2 | HERO12 Black |
     * | 117 | Video Easy Mode Speed 2X Slo Mo 4K 50Hz V2 | HERO12 Black |
     * | 118 | Video Easy Mode Speed Mobile 1X Speed Low Light V2 | HERO12 Black |
     * | 119 | Video Easy Mode Speed Mobile 1X Speed Low Light 50Hz V2 | HERO12 Black |
     * | 120 | Video Easy Mode Speed Mobile 2X Slo Mo V2 | HERO12 Black |
     * | 121 | Video Easy Mode Speed Mobile 2X Slo Mo 50Hz V2 | HERO12 Black |
     * | 122 | Video Easy Mode Speed Universal 1X Speed Low Light V2 | HERO12 Black |
     * | 123 | Video Easy Mode Speed Universal 1X Speed Low Light 50Hz V2 | HERO12 Black |
     *  | 124 | Video Easy Mode Speed Universal 2X Slo Mo V2 | HERO12 Black |
     * | 125 | Video Easy Mode Speed Universal 2X Slo Mo 50Hz V2 | HERO12 Black |
     * | 126 | Video Easy Mode Speed 1X Speed Low Light 4K V2 | HERO12 Black |
     * | 127 | Video Easy Mode Speed 1X Speed Low Light 4K 50Hz V2 | HERO12 Black |
     * | 128 | Video Easy Mode Speed 1X Speed Low Light 2 7K V2 | HERO12 Black |
     * | 129 | Video Easy Mode Speed 1X Speed Low Light 2 7K 50Hz V2 | HERO12 Black |
     * | 130 | Video Easy Mode Speed 2X Slo Mo 2 7K V2 | HERO12 Black |
     * | 131 | Video Easy Mode Speed 2X Slo Mo 2 7K 50Hz V2 | HERO12 Black |
     * | 132 | Video Easy Mode Speed Mobile Lb 2X Slo Mo V2 | HERO12 Black |
     * | 133 | Video Easy Mode Speed Mobile Lb 2X Slo Mo 50Hz V2 | HERO12 Black |
     * | 134 | Video Easy Mode Speed Mobile Lb 1X Speed Low Light V2 | HERO12 Black |
     * | 135 | Video Easy Mode Speed Mobile Lb 1X Speed Low Light 50Hz V2 | HERO12 Black |
     * | 136 | Video Easy Mode Speed Universal 1X Speed Low Light 4K V2 | HERO12 Black |
     * | 137 | Video Easy Mode Speed Universal 1X Speed Low Light 4K 50Hz V2 | HERO12 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _176?: StateSettings_176Enum;
    /**
     * **Photo Easy Mode Night Photo**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO11 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Photo Easy Mode Night Photo Off | HERO11 Black |
     * | 1 | Photo Easy Mode Night Photo On | HERO11 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _177?: StateSettings_177Enum;
    /**
     * **Wireless Wireless Band**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * - HERO11 Black Mini
     * - HERO11 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Wireless Wireless Band 2 4 Ghz | HERO12 Black, HERO11 Black Mini, HERO11 Black |
     * | 1 | Wireless Wireless Band 5 Ghz | HERO12 Black, HERO11 Black Mini, HERO11 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _178?: StateSettings_178Enum;
    /**
     * **Multi Shot Trail Length**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * - HERO11 Black Mini
     * - HERO11 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 1 | Multi Shot Trail Length Short | HERO12 Black, HERO11 Black Mini, HERO11 Black |
     * | 2 | Multi Shot Trail Length Long | HERO12 Black, HERO11 Black Mini, HERO11 Black |
     * | 3 | Multi Shot Trail Length Max | HERO12 Black, HERO11 Black Mini, HERO11 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _179?: StateSettings_179Enum;
    /**
     * **System Video Mode**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO11 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | System Video Mode Highest Quality | HERO11 Black |
     * | 101 | System Video Mode Extended Battery Green | HERO11 Black |
     * | 102 | System Video Mode Longest Battery Green | HERO11 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _180?: StateSettings_180Enum;
    /**
     * **System Video Bit Rate**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | System Video Bit Rate Standard | HERO12 Black |
     * | 1 | System Video Bit Rate High | HERO12 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _182?: StateSettings_182Enum;
    /**
     * **System Video Bit Depth**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | System Video Bit Depth 8Bit | HERO12 Black |
     * | 2 | System Video Bit Depth 10Bit | HERO12 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _183?: StateSettings_183Enum;
    /**
     * **Video Profile**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Video Profile Standard | HERO12 Black |
     * | 1 | Video Profile Hdr | HERO12 Black |
     * | 2 | Video Profile 10 Bit Log | HERO12 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _184?: StateSettings_184Enum;
    /**
     * **Video Easy Presets**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Video Easy Presets Highest Quality | HERO12 Black |
     * | 1 | Video Easy Presets Standard Quality | HERO12 Black |
     * | 2 | Video Easy Presets Basic Quality | HERO12 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _186?: StateSettings_186Enum;
    /**
     * **Multi Shot Easy Presets**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Multi Shot Easy Presets Lapse Mode Time Warp | HERO12 Black |
     * | 1 | Multi Shot Easy Presets Lapse Mode Star Trails | HERO12 Black |
     * | 2 | Multi Shot Easy Presets Lapse Mode Light Painting | HERO12 Black |
     * | 3 | Multi Shot Easy Presets Lapse Mode Vehicle Lights | HERO12 Black |
     * | 4 | Multi Shot Easy Presets Max Lapse Mode Time Warp | HERO12 Black |
     * | 5 | Multi Shot Easy Presets Max Lapse Mode Star Trails | HERO12 Black |
     * | 6 | Multi Shot Easy Presets Max Lapse Mode Light Painting | HERO12 Black |
     * | 7 | Multi Shot Easy Presets Max Lapse Mode Vehicle Lights | HERO12 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _187?: StateSettings_187Enum;
    /**
     * **System Addon Lens Active**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | System Addon Lens Active None | HERO12 Black |
     * | 1 | System Addon Lens Active Max Lens 1 0 | HERO12 Black |
     * | 2 | System Addon Lens Active Max Lens 2 0 | HERO12 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _189?: StateSettings_189Enum;
    /**
     * **System Addon Lens Status**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | System Addon Lens Status Off | HERO12 Black |
     * | 1 | System Addon Lens Status On | HERO12 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _190?: StateSettings_190Enum;
    /**
     * **Photo Easy Presets**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Photo Easy Presets Super Photo | HERO12 Black |
     *  | 1 | Photo Easy Presets Night Photo | HERO12 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _191?: StateSettings_191Enum;
    /**
     * **Multi Shot Nlv Aspect Ratio**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Multi Shot Nlv Aspect Ratio 4By3 | HERO12 Black |
     * | 1 | Multi Shot Nlv Aspect Ratio 16By9 | HERO12 Black |
     * | 3 | Multi Shot Nlv Aspect Ratio 8By7 | HERO12 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _192?: StateSettings_192Enum;
    /**
     * **Video Easy Framing**
     * 
     * Supported Cameras:
     * 
     * 
     * - HERO12 Black
     * 
     * 
     * | Value | Meaning |  Supported Cameras |
     * | ----- | ------- |  ----------------- |
     * | 0 | Video Easy Framing Widescreen | HERO12 Black |
     *  | 1 | Video Easy Framing Vertical | HERO12 Black |
     * | 2 | Video Easy Framing Full Frame | HERO12 Black |
     * 
     * @type {number}
     * @memberof StateSettings
     */
    _193?: StateSettings_193Enum;
}


/**
 * @export
 */
export const StateSettings_2Enum = {
    NUMBER_1: 1,
    NUMBER_4: 4,
    NUMBER_6: 6,
    NUMBER_7: 7,
    NUMBER_9: 9,
    NUMBER_18: 18,
    NUMBER_24: 24,
    NUMBER_25: 25,
    NUMBER_26: 26,
    NUMBER_27: 27,
    NUMBER_28: 28,
    NUMBER_100: 100,
    NUMBER_107: 107,
    NUMBER_108: 108,
    NUMBER_109: 109,
    NUMBER_110: 110,
    NUMBER_111: 111
} as const;
export type StateSettings_2Enum = typeof StateSettings_2Enum[keyof typeof StateSettings_2Enum];

/**
 * @export
 */
export const StateSettings_3Enum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_8: 8,
    NUMBER_9: 9,
    NUMBER_10: 10,
    NUMBER_13: 13
} as const;
export type StateSettings_3Enum = typeof StateSettings_3Enum[keyof typeof StateSettings_3Enum];

/**
 * @export
 */
export const StateSettings_43Enum = {
    NUMBER_0: 0,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type StateSettings_43Enum = typeof StateSettings_43Enum[keyof typeof StateSettings_43Enum];

/**
 * @export
 */
export const StateSettings_59Enum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_4: 4,
    NUMBER_6: 6,
    NUMBER_7: 7,
    NUMBER_11: 11,
    NUMBER_12: 12
} as const;
export type StateSettings_59Enum = typeof StateSettings_59Enum[keyof typeof StateSettings_59Enum];

/**
 * @export
 */
export const StateSettings_108Enum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type StateSettings_108Enum = typeof StateSettings_108Enum[keyof typeof StateSettings_108Enum];

/**
 * @export
 */
export const StateSettings_121Enum = {
    NUMBER_0: 0,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_7: 7,
    NUMBER_8: 8,
    NUMBER_9: 9,
    NUMBER_10: 10,
    NUMBER_11: 11
} as const;
export type StateSettings_121Enum = typeof StateSettings_121Enum[keyof typeof StateSettings_121Enum];

/**
 * @export
 */
export const StateSettings_122Enum = {
    NUMBER_19: 19,
    NUMBER_100: 100,
    NUMBER_101: 101,
    NUMBER_102: 102
} as const;
export type StateSettings_122Enum = typeof StateSettings_122Enum[keyof typeof StateSettings_122Enum];

/**
 * @export
 */
export const StateSettings_123Enum = {
    NUMBER_19: 19,
    NUMBER_100: 100,
    NUMBER_101: 101,
    NUMBER_102: 102
} as const;
export type StateSettings_123Enum = typeof StateSettings_123Enum[keyof typeof StateSettings_123Enum];

/**
 * @export
 */
export const StateSettings_128Enum = {
    NUMBER_13: 13,
    NUMBER_20: 20,
    NUMBER_21: 21,
    NUMBER_26: 26
} as const;
export type StateSettings_128Enum = typeof StateSettings_128Enum[keyof typeof StateSettings_128Enum];

/**
 * @export
 */
export const StateSettings_134Enum = {
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type StateSettings_134Enum = typeof StateSettings_134Enum[keyof typeof StateSettings_134Enum];

/**
 * @export
 */
export const StateSettings_135Enum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_100: 100
} as const;
export type StateSettings_135Enum = typeof StateSettings_135Enum[keyof typeof StateSettings_135Enum];

/**
 * @export
 */
export const StateSettings_150Enum = {
    NUMBER_0: 0,
    NUMBER_2: 2
} as const;
export type StateSettings_150Enum = typeof StateSettings_150Enum[keyof typeof StateSettings_150Enum];

/**
 * @export
 */
export const StateSettings_151Enum = {
    NUMBER_0: 0,
    NUMBER_2: 2
} as const;
export type StateSettings_151Enum = typeof StateSettings_151Enum[keyof typeof StateSettings_151Enum];

/**
 * @export
 */
export const StateSettings_162Enum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type StateSettings_162Enum = typeof StateSettings_162Enum[keyof typeof StateSettings_162Enum];

/**
 * @export
 */
export const StateSettings_167Enum = {
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;
export type StateSettings_167Enum = typeof StateSettings_167Enum[keyof typeof StateSettings_167Enum];

/**
 * @export
 */
export const StateSettings_171Enum = {
    NUMBER_0: 0,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7,
    NUMBER_8: 8,
    NUMBER_9: 9,
    NUMBER_10: 10
} as const;
export type StateSettings_171Enum = typeof StateSettings_171Enum[keyof typeof StateSettings_171Enum];

/**
 * @export
 */
export const StateSettings_172Enum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7,
    NUMBER_8: 8,
    NUMBER_9: 9
} as const;
export type StateSettings_172Enum = typeof StateSettings_172Enum[keyof typeof StateSettings_172Enum];

/**
 * @export
 */
export const StateSettings_173Enum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type StateSettings_173Enum = typeof StateSettings_173Enum[keyof typeof StateSettings_173Enum];

/**
 * @export
 */
export const StateSettings_175Enum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type StateSettings_175Enum = typeof StateSettings_175Enum[keyof typeof StateSettings_175Enum];

/**
 * @export
 */
export const StateSettings_176Enum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7,
    NUMBER_8: 8,
    NUMBER_9: 9,
    NUMBER_10: 10,
    NUMBER_11: 11,
    NUMBER_12: 12,
    NUMBER_13: 13,
    NUMBER_14: 14,
    NUMBER_15: 15,
    NUMBER_16: 16,
    NUMBER_17: 17,
    NUMBER_18: 18,
    NUMBER_19: 19,
    NUMBER_20: 20,
    NUMBER_21: 21,
    NUMBER_22: 22,
    NUMBER_23: 23,
    NUMBER_24: 24,
    NUMBER_25: 25,
    NUMBER_26: 26,
    NUMBER_27: 27,
    NUMBER_100: 100,
    NUMBER_101: 101,
    NUMBER_102: 102,
    NUMBER_103: 103,
    NUMBER_104: 104,
    NUMBER_105: 105,
    NUMBER_106: 106,
    NUMBER_107: 107,
    NUMBER_108: 108,
    NUMBER_109: 109,
    NUMBER_110: 110,
    NUMBER_111: 111,
    NUMBER_112: 112,
    NUMBER_113: 113,
    NUMBER_114: 114,
    NUMBER_115: 115,
    NUMBER_116: 116,
    NUMBER_117: 117,
    NUMBER_118: 118,
    NUMBER_119: 119,
    NUMBER_120: 120,
    NUMBER_121: 121,
    NUMBER_122: 122,
    NUMBER_123: 123,
    NUMBER_124: 124,
    NUMBER_125: 125,
    NUMBER_126: 126,
    NUMBER_127: 127,
    NUMBER_128: 128,
    NUMBER_129: 129,
    NUMBER_130: 130,
    NUMBER_131: 131,
    NUMBER_132: 132,
    NUMBER_133: 133,
    NUMBER_134: 134,
    NUMBER_135: 135,
    NUMBER_136: 136,
    NUMBER_137: 137
} as const;
export type StateSettings_176Enum = typeof StateSettings_176Enum[keyof typeof StateSettings_176Enum];

/**
 * @export
 */
export const StateSettings_177Enum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type StateSettings_177Enum = typeof StateSettings_177Enum[keyof typeof StateSettings_177Enum];

/**
 * @export
 */
export const StateSettings_178Enum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type StateSettings_178Enum = typeof StateSettings_178Enum[keyof typeof StateSettings_178Enum];

/**
 * @export
 */
export const StateSettings_179Enum = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type StateSettings_179Enum = typeof StateSettings_179Enum[keyof typeof StateSettings_179Enum];

/**
 * @export
 */
export const StateSettings_180Enum = {
    NUMBER_0: 0,
    NUMBER_101: 101,
    NUMBER_102: 102
} as const;
export type StateSettings_180Enum = typeof StateSettings_180Enum[keyof typeof StateSettings_180Enum];

/**
 * @export
 */
export const StateSettings_182Enum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type StateSettings_182Enum = typeof StateSettings_182Enum[keyof typeof StateSettings_182Enum];

/**
 * @export
 */
export const StateSettings_183Enum = {
    NUMBER_0: 0,
    NUMBER_2: 2
} as const;
export type StateSettings_183Enum = typeof StateSettings_183Enum[keyof typeof StateSettings_183Enum];

/**
 * @export
 */
export const StateSettings_184Enum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type StateSettings_184Enum = typeof StateSettings_184Enum[keyof typeof StateSettings_184Enum];

/**
 * @export
 */
export const StateSettings_186Enum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type StateSettings_186Enum = typeof StateSettings_186Enum[keyof typeof StateSettings_186Enum];

/**
 * @export
 */
export const StateSettings_187Enum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6,
    NUMBER_7: 7
} as const;
export type StateSettings_187Enum = typeof StateSettings_187Enum[keyof typeof StateSettings_187Enum];

/**
 * @export
 */
export const StateSettings_189Enum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type StateSettings_189Enum = typeof StateSettings_189Enum[keyof typeof StateSettings_189Enum];

/**
 * @export
 */
export const StateSettings_190Enum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type StateSettings_190Enum = typeof StateSettings_190Enum[keyof typeof StateSettings_190Enum];

/**
 * @export
 */
export const StateSettings_191Enum = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type StateSettings_191Enum = typeof StateSettings_191Enum[keyof typeof StateSettings_191Enum];

/**
 * @export
 */
export const StateSettings_192Enum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_3: 3
} as const;
export type StateSettings_192Enum = typeof StateSettings_192Enum[keyof typeof StateSettings_192Enum];

/**
 * @export
 */
export const StateSettings_193Enum = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;
export type StateSettings_193Enum = typeof StateSettings_193Enum[keyof typeof StateSettings_193Enum];


/**
 * Check if a given object implements the StateSettings interface.
 */
export function instanceOfStateSettings(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StateSettingsFromJSON(json: any): StateSettings {
    return StateSettingsFromJSONTyped(json, false);
}

export function StateSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): StateSettings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_2': !exists(json, '2') ? undefined : json['2'],
        '_3': !exists(json, '3') ? undefined : json['3'],
        '_43': !exists(json, '43') ? undefined : json['43'],
        '_59': !exists(json, '59') ? undefined : json['59'],
        '_108': !exists(json, '108') ? undefined : json['108'],
        '_121': !exists(json, '121') ? undefined : json['121'],
        '_122': !exists(json, '122') ? undefined : json['122'],
        '_123': !exists(json, '123') ? undefined : json['123'],
        '_128': !exists(json, '128') ? undefined : json['128'],
        '_134': !exists(json, '134') ? undefined : json['134'],
        '_135': !exists(json, '135') ? undefined : json['135'],
        '_150': !exists(json, '150') ? undefined : json['150'],
        '_151': !exists(json, '151') ? undefined : json['151'],
        '_162': !exists(json, '162') ? undefined : json['162'],
        '_167': !exists(json, '167') ? undefined : json['167'],
        '_171': !exists(json, '171') ? undefined : json['171'],
        '_172': !exists(json, '172') ? undefined : json['172'],
        '_173': !exists(json, '173') ? undefined : json['173'],
        '_175': !exists(json, '175') ? undefined : json['175'],
        '_176': !exists(json, '176') ? undefined : json['176'],
        '_177': !exists(json, '177') ? undefined : json['177'],
        '_178': !exists(json, '178') ? undefined : json['178'],
        '_179': !exists(json, '179') ? undefined : json['179'],
        '_180': !exists(json, '180') ? undefined : json['180'],
        '_182': !exists(json, '182') ? undefined : json['182'],
        '_183': !exists(json, '183') ? undefined : json['183'],
        '_184': !exists(json, '184') ? undefined : json['184'],
        '_186': !exists(json, '186') ? undefined : json['186'],
        '_187': !exists(json, '187') ? undefined : json['187'],
        '_189': !exists(json, '189') ? undefined : json['189'],
        '_190': !exists(json, '190') ? undefined : json['190'],
        '_191': !exists(json, '191') ? undefined : json['191'],
        '_192': !exists(json, '192') ? undefined : json['192'],
        '_193': !exists(json, '193') ? undefined : json['193'],
    };
}

export function StateSettingsToJSON(value?: StateSettings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '2': value._2,
        '3': value._3,
        '43': value._43,
        '59': value._59,
        '108': value._108,
        '121': value._121,
        '122': value._122,
        '123': value._123,
        '128': value._128,
        '134': value._134,
        '135': value._135,
        '150': value._150,
        '151': value._151,
        '162': value._162,
        '167': value._167,
        '171': value._171,
        '172': value._172,
        '173': value._173,
        '175': value._175,
        '176': value._176,
        '177': value._177,
        '178': value._178,
        '179': value._179,
        '180': value._180,
        '182': value._182,
        '183': value._183,
        '184': value._184,
        '186': value._186,
        '187': value._187,
        '189': value._189,
        '190': value._190,
        '191': value._191,
        '192': value._192,
        '193': value._193,
    };
}

